name: Deploy Web SalaG

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Acesso EC2
        run: |
          echo "${{ secrets.SECRETS_KEY_E }}" > site-apache-estudo.pem
          chmod 600 site-apache-estudo.pem
          ssh -o StrictHostKeyChecking=no -i "site-apache-estudo.pem" ubuntu@ec2-174-129-248-19.compute-1.amazonaws.com << 'EOF'
            cd /var/www/html/sitePraticaE
            git checkout main
            git pull origin main
          EOF
